# Generated by Django 5.1.4 on 2026-05-18 04:36

import apps.prestamos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_esperada', models.DateField(default=apps.prestamos.models.fecha_devolucion_default)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido')], db_index=True, default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.ejemplar')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Personal de biblioteca que registró el préstamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='usuarios.usuariobiblioteca')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
                'indexes': [models.Index(fields=['estado', 'fecha_devolucion_esperada'], name='prestamos_p_estado_fef722_idx')],
            },
        ),
    ]
