# Generated by Django 5.1.4 on 2026-05-19 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('POR_VENCER', 'Préstamo por vencer'), ('VENCIDO', 'Préstamo vencido')], db_index=True, max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARN', 'Advertencia'), ('CRIT', 'Crítica')], db_index=True, default='INFO', max_length=10)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField(blank=True)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('leida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_marcadas', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['leida', '-creada_en'],
                'indexes': [models.Index(fields=['leida', '-creada_en'], name='alertas_ale_leida_03c7d5_idx'), models.Index(fields=['tipo', 'leida'], name='alertas_ale_tipo_71dd66_idx')],
            },
        ),
    ]
