# Generated by Django 5.1.4 on 2026-05-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('codigo_corto', models.CharField(help_text='Ej: ECON, ADM, CONT, CNI', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('editorial', models.CharField(blank=True, max_length=150)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('numero_paginas', models.PositiveIntegerField(blank=True, null=True, verbose_name='N° de páginas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='catalogo.categoria', verbose_name='Categoría / Escuela')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del ejemplar. Es el que lee el código de barras (ej: L-ECON-0001).', max_length=50, unique=True)),
                ('clasificacion', models.CharField(blank=True, help_text='Clasificación bibliográfica / signatura (ej: 338.5A59E.1)', max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=50, verbose_name='Ubicación física')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('BAJA', 'Dado de baja')], db_index=True, default='DISPONIBLE', max_length=15)),
                ('condicion', models.CharField(choices=[('BUENO', 'Buen estado'), ('REGULAR', 'Regular'), ('MALO', 'Mal estado')], default='BUENO', max_length=10, verbose_name='Condición física')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalogo.libro')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=400)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='catalogo.libro')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['libro', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='catalogo_li_titulo_767fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='catalogo_li_autor_044b17_idx'),
        ),
    ]
