# Generated by Django 5.1.4 on 2026-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_universitario', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código universitario')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMIN', 'Administrativo')], default='ESTUDIANTE', max_length=15)),
                ('escuela', models.CharField(blank=True, help_text='Escuela profesional (Economía, Administración, etc.)', max_length=80)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no podrá pedir nuevos préstamos.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario de Biblioteca',
                'verbose_name_plural': 'Usuarios de Biblioteca',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
