# Generated by Django 5.1.4 on 2026-05-19 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('TARDIA', 'Devolución tardía'), ('DANO', 'Libro dañado'), ('PERDIDO', 'Libro perdido'), ('COMPORT', 'Comportamiento inadecuado'), ('OTRO', 'Otro motivo')], max_length=10)),
                ('tipo', models.CharField(choices=[('TEMP', 'Bloqueo temporal'), ('INDEF', 'Bloqueo indefinido'), ('ADV', 'Advertencia (sin bloqueo)')], default='TEMP', max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del incidente (opcional).')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo para bloqueo temporal.', null=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('levantada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_levantamiento', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('levantada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_levantadas', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(blank=True, help_text='Préstamo que originó la sanción (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_originadas', to='prestamos.prestamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='usuarios.usuariobiblioteca')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['activa', 'tipo'], name='usuarios_sa_activa_f44eab_idx')],
            },
        ),
    ]
